export const NO_SYNC_COUNTRIES = [
    'North Korea',
    'Somalia',
    'Afghanistan',
    'Pakistan',
    'Sudan',
    'Syria',
    'Iraq',
    'Iran',
    'Yemen',
    'Eritrea',
    'Libya',
    'Nigeria',
    'Maldives',
    'Saudi Arabia',
    'India',
    'Uzbekistan',
    'Vietnam',
    'Kenya',
    'Turkmenistan',
    'Qatar',
    'Egypt',
    'Ethiopia',
    'Palestinian Territories',
    'Laos',
    'Brunei',
    'Bangladesh',
    'Jordan',
    'Myanmar',
    'Tunisia',
    'Bhutan',
    'Malaysia',
    'Mali',
    'Tanzania',
    'Central African Republic',
    'Tajikistan',
    'Algeria',
    'Turkey',
    'Kuwait',
    'China',
    'Djibouti',
    'Mexico',
    'Comoros',
    'Kazakhstan',
    'United Arab Emirates',
    'Sri Lanka',
    'Indonesia',
    'Mauritania',
    'Bahrain',
    'Oman',
    'Colombia',
    'Cuba',
]